services:
  postgres-sql-bsn:       # Base de donnees
    container_name: postgres-sql-bsn
    image: postgres:16.3-bullseye
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    #networks:
      #- spring-demo
    restart: no

  mail-dev:        # serveur pour les mails
    container_name: mail-dev-bsn
    image: maildev/maildev
    restart: no
    ports:
      - 1080:1080
      - 1025:1025



networks:
  spring-demo:
    driver: bridge


volumes:
  postgres:
    driver: local