services:
  postgres-sql-bsn:       # Base de donnees
    container_name: postgres-sql-bsn
    image: postgres:16.3-bullseye
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: no

  mail-dev:        # serveur pour les mails
    container_name: mail-dev-bsn
    image: maildev/maildev
    restart: no
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo


  bsn-api:         # image docker de notre api
    container_name: bsn-api
    image: sonnyhardy/bsn-api:1.0.0
    restart: no
    ports:
      - 8082:8082
    networks:
      - spring-demo
    depends_on:
      - postgres-sql-bsn

  bsn-ui:
    container_name: bsn-ui
    image: sonnyhardy/bsn-ui:1.0.0
    restart: no
    ports:
      - 8083:80
    networks:
      - spring-demo
    depends_on:
      - bsn-api

  keycloak:
    container_name: keycloak-bsn
    image: keycloak/keycloak:25.0.6
    restart: no
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"


networks:
  spring-demo:
    driver: bridge


volumes:
  postgres:
    driver: local